menu:
    Blog: /
    Archive: /archives/
    Projects: /projects/
    About: /about/
    GitHub: https://github.com/crowser
    Rss: /atom.xml

favicon: /favicon.png
logo: /logo.png

# Comment
# e.g disqus: seansun
disqus: crowsers-blog
# duoshuo:

# Analytics
# google-analytics:
ga: UA-120220174-1

# Copyright Infomation
startyear: 2018
